"""Initial multi-sport schema

Revision ID: 3bde1e271421
Revises: 
Create Date: 2025-12-25 06:32:09.815811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bde1e271421'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('league_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('league_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_calibration',
    sa.Column('calibration_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('calibration_date', sa.DateTime(), nullable=True),
    sa.Column('win_prob_accuracy', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('spread_mae', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('spread_cover_accuracy', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('total_mae', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('over_under_accuracy', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('roi_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('profitable_bets', sa.Integer(), nullable=True),
    sa.Column('total_bets_backtested', sa.Integer(), nullable=True),
    sa.Column('brier_score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('log_loss', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('calibration_id')
    )
    op.create_index('ix_calibration_season', 'model_calibration', ['season'], unique=False)
    op.create_index('ix_calibration_version', 'model_calibration', ['model_version'], unique=False)
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('height', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('college', sa.String(length=100), nullable=True),
    sa.Column('draft_year', sa.Integer(), nullable=True),
    sa.Column('draft_round', sa.Integer(), nullable=True),
    sa.Column('draft_pick', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index('ix_players_external', 'players', ['external_id'], unique=False)
    op.create_index('ix_players_name', 'players', ['last_name', 'first_name'], unique=False)
    op.create_table('simulations',
    sa.Column('simulation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('simulation_name', sa.String(length=200), nullable=True),
    sa.Column('simulation_type', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('num_iterations', sa.Integer(), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_time_seconds', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    op.create_index('ix_simulations_league_season', 'simulations', ['league_id', 'season'], unique=False)
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('conference', sa.String(length=50), nullable=True),
    sa.Column('division', sa.String(length=50), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('off_rating', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('def_rating', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pace', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pass_yards_per_game', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rush_yards_per_game', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('points_per_game', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('points_allowed_per_game', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index('ix_teams_abbrev', 'teams', ['abbreviation'], unique=False)
    op.create_index('ix_teams_league_season', 'teams', ['league_id', 'season'], unique=False)
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_historical', sa.Boolean(), nullable=True),
    sa.Column('opening_spread', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('closing_spread', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('opening_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('closing_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('home_ml_odds', sa.Integer(), nullable=True),
    sa.Column('away_ml_odds', sa.Integer(), nullable=True),
    sa.Column('weather_temp', sa.Integer(), nullable=True),
    sa.Column('weather_wind', sa.Integer(), nullable=True),
    sa.Column('weather_condition', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index('ix_games_date', 'games', ['game_date'], unique=False)
    op.create_index('ix_games_external', 'games', ['external_id'], unique=False)
    op.create_index('ix_games_season_week', 'games', ['season', 'week'], unique=False)
    op.create_table('player_season_stats',
    sa.Column('stat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('pass_attempts', sa.Integer(), nullable=True),
    sa.Column('pass_completions', sa.Integer(), nullable=True),
    sa.Column('pass_yards', sa.Integer(), nullable=True),
    sa.Column('pass_touchdowns', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('passer_rating', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rush_attempts', sa.Integer(), nullable=True),
    sa.Column('rush_yards', sa.Integer(), nullable=True),
    sa.Column('rush_touchdowns', sa.Integer(), nullable=True),
    sa.Column('yards_per_carry', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('receptions', sa.Integer(), nullable=True),
    sa.Column('targets', sa.Integer(), nullable=True),
    sa.Column('receiving_yards', sa.Integer(), nullable=True),
    sa.Column('receiving_touchdowns', sa.Integer(), nullable=True),
    sa.Column('yards_per_reception', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('points', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('rebounds', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assists', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('steals', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('blocks', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('field_goal_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('three_pt_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('free_throw_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('minutes_per_game', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fantasy_points_ppr', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fantasy_points_half_ppr', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fantasy_points_standard', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('projected_fantasy_points', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('stat_id')
    )
    op.create_index('ix_player_stats_season', 'player_season_stats', ['player_id', 'season'], unique=False)
    op.create_index('ix_player_stats_team', 'player_season_stats', ['team_id', 'season'], unique=False)
    op.create_table('betting_odds',
    sa.Column('odds_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('home_ml', sa.Integer(), nullable=True),
    sa.Column('away_ml', sa.Integer(), nullable=True),
    sa.Column('spread', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('spread_home_odds', sa.Integer(), nullable=True),
    sa.Column('spread_away_odds', sa.Integer(), nullable=True),
    sa.Column('total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('over_odds', sa.Integer(), nullable=True),
    sa.Column('under_odds', sa.Integer(), nullable=True),
    sa.Column('is_opening', sa.Boolean(), nullable=True),
    sa.Column('is_closing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('odds_id')
    )
    op.create_index('ix_odds_game', 'betting_odds', ['game_id'], unique=False)
    op.create_index('ix_odds_timestamp', 'betting_odds', ['timestamp'], unique=False)
    op.create_table('simulation_results',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('home_win_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('away_win_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('tie_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('expected_spread', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('spread_std_dev', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cover_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('expected_total_points', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_std_dev', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('over_under_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('home_score_median', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('home_score_mean', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('home_score_p10', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('home_score_p25', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('home_score_p75', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('home_score_p90', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('away_score_median', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('away_score_mean', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('away_score_p10', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('away_score_p25', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('away_score_p75', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('away_score_p90', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('distribution_json', sa.JSON(), nullable=True),
    sa.Column('edge_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ev_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('confidence_tier', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.simulation_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index('ix_sim_results_game', 'simulation_results', ['game_id'], unique=False)
    op.create_index('ix_sim_results_season', 'simulation_results', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sim_results_season', table_name='simulation_results')
    op.drop_index('ix_sim_results_game', table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index('ix_odds_timestamp', table_name='betting_odds')
    op.drop_index('ix_odds_game', table_name='betting_odds')
    op.drop_table('betting_odds')
    op.drop_index('ix_player_stats_team', table_name='player_season_stats')
    op.drop_index('ix_player_stats_season', table_name='player_season_stats')
    op.drop_table('player_season_stats')
    op.drop_index('ix_games_season_week', table_name='games')
    op.drop_index('ix_games_external', table_name='games')
    op.drop_index('ix_games_date', table_name='games')
    op.drop_table('games')
    op.drop_index('ix_teams_league_season', table_name='teams')
    op.drop_index('ix_teams_abbrev', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_simulations_league_season', table_name='simulations')
    op.drop_table('simulations')
    op.drop_index('ix_players_name', table_name='players')
    op.drop_index('ix_players_external', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_calibration_version', table_name='model_calibration')
    op.drop_index('ix_calibration_season', table_name='model_calibration')
    op.drop_table('model_calibration')
    op.drop_table('leagues')
    # ### end Alembic commands ###
